### ISSUE TITLE
Events not fired with the latest version

### ISSUE THREAD

**Issue by DonsWayo** [revolist/react-datagrid#8]
Hi,

Events are not fired with the latest version, here is a Codesanbox example:

https://codesandbox.io/s/laughing-dan-hu4yly?file=/src/App.js

**Comment by tobiasBora** [comment]
Any news on this? I get the same problem, and it’s quite annoying as we can’t customize the behavior…

**Comment by m2a2x** [comment]
All Events are lowercased, meaning onAfteredit, please follow the doc https://github.com/revolist/revogrid/blob/master/src/components/revo-grid/readme.md

**Comment by m2a2x** [comment]
https://codesandbox.io/s/crazy-boyd-8pzj53?file=/src/App.js:885-896
