### ISSUE TITLE
How to embed an SPFx People Picker as a cell?

### ISSUE THREAD

**Issue by sean-phyx** [revolist/react-datagrid#9]
Hi, I am trying to embed an SPFx People picker as a cell and have created this adapter:
```js
    private peoplePickerAdapter(parent, props) {
        let wrapper;
        if (parent.childNodes.length) {
          wrapper = parent.childNodes[0];
          ReactDOM.unmountComponentAtNode(wrapper);
        } else {
          wrapper = document.createElement("span");
          parent.appendChild(wrapper);
        }
        ReactDOM.render(
        <PeoplePicker 
            context={this.props.context}
            groupName={""}
            showtooltip={false}
            personSelectionLimit={1}
            defaultSelectedUsers={[this.state.picsList[0]]}
            onChange={(items: any[]) => {
                if (items.length != 0) {
                props.model.PICFound.User = items[0];
                } else {
                props.model.PICFound.User = null;
                }
            }}
            principalTypes={[PrincipalType.User]} />
        // <button className='btn btn-primary' style={ {width: "225px"} } type='button' id='btnChangeView' onClick={ async () => { await this.setState( {peopleModalOpen: !this.state.peopleModalOpen} )} } >
        //     {props.model.PICFound.User ? props.model.PICFound.User.Title : "Select PIC"}
        // </button>
        , wrapper);
    }
```

However, this displays the component but when trying to type in the component it types within the cell. This will not work as the people picker relies on the input of the component to search the users. Is there a way to have the cell level typing turned off and the inputs sent to the component instead of the cell?

The strange thing is that the people picker just doesn't seem to show any sort of data when embeded in the cell.

this is the specific component I'd like to have the functionality of:
https://pnp.github.io/sp-dev-fx-controls-react/controls/PeoplePicker/
    
I believe an editor is the way however there is not much documentation on the usage of this. Or I am just not experienced enough to implement with the information given. Does anyone know how this could be achieved?

**Comment by revolist** [comment]
I would recommend to use tsx native render. If picker is react component then just use our new react component wrapper
